schema-version: v1
kind: plugin
metadata:
  name: android-sdk
  display-name: android-sdk
  description: criar um sdk android
  version: 0.0.1
  picture: plugin.png
spec:
  type: app
  compatibility:
    - python
  about: docs/about.md
  implementation: docs/implementation.md
  release-notes: docs/release-notes-0.0.1.md
  requirements: docs/requirements.md
  repository: git@github.com:FernandaAbreuZup/stackspot-android-sdk.git
  technologies: # Ref: https://docs.stackspot.com/content-creator/studio/yaml-files/plugin-yaml/#technologies
    - Api
  inputs:
  - label: "Digite o nome do projeto"
    name: "project_name"
    type: "text"
    default: "Project Name"
    required: true
    global: true
  - label: "Digite a descrição do projeto"
    name: "project_description"
    type: "text"
    required: true
    global: true
  - label: "Digite o Group ID: ( o seu package name sem o nome do modulo no final)"
    name: "init_package_name"
    type: "text"
    required: true
    global: true
  - label: "Digite o Minimum SDK:"
    name: "minimum_sdk"
    type: "text"
    default: "21"
    global: true
  global-computed-inputs:
    module_name: "{{project_name|lower|replace('-', '.')|replace('_', '.')}}"
